//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCAS_capture_payments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VCAS_capture_payments()
        {
            this.VCAS_creditTrans1 = new HashSet<VCAS_creditTrans>();
        }
    
        public int Id { get; set; }
        public System.DateTime datetime { get; set; }
        public string payer { get; set; }
        public double amount { get; set; }
        public Nullable<int> checkNo { get; set; }
        public string comment { get; set; }
        public string receiptNo { get; set; }
        public string issuer { get; set; }
        public bool voidCheck { get; set; }
        public int FK_paymentType { get; set; }
        public int FK_bankDetails { get; set; }
        public int FK_items { get; set; }
        public int FK_location { get; set; }
        public Nullable<int> payerID { get; set; }
        public Nullable<int> orderID { get; set; }
        public Nullable<bool> invoice { get; set; }
        public Nullable<double> recieved_amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VCAS_creditTrans> VCAS_creditTrans1 { get; set; }
        public virtual VCAS_council VCAS_council { get; set; }
        public virtual VCAS_REF_bank_details VCAS_REF_bank_details { get; set; }
        public virtual VCAS_REF_items VCAS_REF_items { get; set; }
        public virtual VCAS_REF_payment_type VCAS_REF_payment_type { get; set; }
    }
}
