
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VCAS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VCAS_reports
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public VCAS_reports()
    {

        this.VCAS_REF_reports_params = new HashSet<VCAS_REF_reports_params>();

    }


    public int Id { get; set; }

    public string name { get; set; }

    public string desc { get; set; }

    public int FK_REF_userRolesId { get; set; }

    public bool paramCheck { get; set; }



    public virtual VCAS_REF_userRoles VCAS_REF_userRoles { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VCAS_REF_reports_params> VCAS_REF_reports_params { get; set; }

}

}
