//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCAS_supportDocs
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public string media { get; set; }
        public string media_type { get; set; }
        public int FK_REF_userRolesId { get; set; }
    
        public virtual VCAS_REF_userRoles VCAS_REF_userRoles { get; set; }
    }
}
