//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCAS_REF_processes
    {
        public int Id { get; set; }
        public string param_key { get; set; }
        public string param_value { get; set; }
        public string param_dataType { get; set; }
        public int FK_processesId { get; set; }
    
        public virtual VCAS_processes VCAS_processes { get; set; }
    }
}
