
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VCAS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VCAS_debitAccounts
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public VCAS_debitAccounts()
    {

        this.VCAS_debitTrans = new HashSet<VCAS_debitTrans>();

        this.VCAS_issuedChecks = new HashSet<VCAS_issuedChecks>();

    }


    public int Id { get; set; }

    public string name { get; set; }

    public string acctNum { get; set; }

    public Nullable<double> amount { get; set; }

    public int FK_payment_Type { get; set; }

    public string remittance { get; set; }

    public string payee { get; set; }

    public System.DateTime datetime { get; set; }

    public string attach_statement { get; set; }

    public int FK_location { get; set; }



    public virtual VCAS_REF_payment_type VCAS_REF_payment_type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VCAS_debitTrans> VCAS_debitTrans { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VCAS_issuedChecks> VCAS_issuedChecks { get; set; }

    public virtual VCAS_council VCAS_council { get; set; }

}

}
