
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VCAS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VCAS_inventory
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public VCAS_inventory()
    {

        this.VCAS_orders = new HashSet<VCAS_orders>();

    }


    public int Id { get; set; }

    public string name { get; set; }

    public string desc { get; set; }

    public System.DateTime dateModified { get; set; }

    public string partNumber { get; set; }

    public string label { get; set; }

    public double startStock { get; set; }

    public Nullable<double> currentStock { get; set; }

    public Nullable<double> quantity { get; set; }

    public Nullable<double> size { get; set; }

    public string unit { get; set; }

    public Nullable<double> unitPrice { get; set; }

    public Nullable<double> sellingPrice { get; set; }

    public string image { get; set; }

    public Nullable<int> FK_REF_itemsId { get; set; }

    public Nullable<int> FK_location { get; set; }



    public virtual VCAS_council VCAS_council { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VCAS_orders> VCAS_orders { get; set; }

    public virtual VCAS_REF_items VCAS_REF_items { get; set; }

}

}
