//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCAS_links
    {
        public int Id { get; set; }
        public string text { get; set; }
        public string action { get; set; }
        public string controller { get; set; }
        public int FK_location { get; set; }
        public int FK_REF_userRolesId { get; set; }
    
        public virtual VCAS_council VCAS_council { get; set; }
        public virtual VCAS_REF_userRoles VCAS_REF_userRoles { get; set; }
    }
}
