
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VCAS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VCAS_issuedChecks
{

    public int Id { get; set; }

    public Nullable<System.DateTime> datetime { get; set; }

    public double amount { get; set; }

    public string checkNo { get; set; }

    public string issuer { get; set; }

    public string receiverName { get; set; }

    public int FK_receiverID_TypesId { get; set; }

    public string receiverID { get; set; }

    public string signature { get; set; }

    public int FK_debitAccountsId { get; set; }

    public int FK_location { get; set; }

    public string approver { get; set; }

    public Nullable<int> approval { get; set; }

    public Nullable<int> pending_approval { get; set; }

    public string auth_signature { get; set; }

    public Nullable<bool> complete { get; set; }

    public Nullable<int> FK_expensesId { get; set; }

    public string attach_ID { get; set; }

    public string attach_Doc { get; set; }

    public string attach_Receipt { get; set; }

    public string comments { get; set; }



    public virtual VCAS_expenses VCAS_expenses { get; set; }

    public virtual VCAS_REF_receiverID_Types VCAS_REF_receiverID_Types { get; set; }

    public virtual VCAS_council VCAS_council { get; set; }

    public virtual VCAS_debitAccounts VCAS_debitAccounts { get; set; }

}

}
