
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VCAS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VCAS_inventory_AUDIT
{

    public int Id { get; set; }

    public string name { get; set; }

    public Nullable<double> startStock { get; set; }

    public Nullable<double> currentStock { get; set; }

    public Nullable<int> FK_REF_itemsId { get; set; }

    public Nullable<System.DateTime> datetime { get; set; }

}

}
