//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCAS_processes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VCAS_processes()
        {
            this.VCAS_REF_processes = new HashSet<VCAS_REF_processes>();
        }
    
        public int Id { get; set; }
        public string sp_name { get; set; }
        public int FK_location { get; set; }
    
        public virtual VCAS_council VCAS_council { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VCAS_REF_processes> VCAS_REF_processes { get; set; }
    }
}
