//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCAS_REF_reports_params
    {
        public int Id { get; set; }
        public string param_key { get; set; }
        public string param_value { get; set; }
        public string param_dataType { get; set; }
        public int FK_REF_reportsId { get; set; }
        public Nullable<int> FK_location { get; set; }
    
        public virtual VCAS_reports VCAS_reports { get; set; }
        public virtual VCAS_council VCAS_council { get; set; }
    }
}
