
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VCAS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VCAS_council
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public VCAS_council()
    {

        this.VCAS_debitAccounts = new HashSet<VCAS_debitAccounts>();

        this.VCAS_district = new HashSet<VCAS_district>();

        this.VCAS_issuedChecks = new HashSet<VCAS_issuedChecks>();

        this.VCAS_REF_expense_location = new HashSet<VCAS_REF_expense_location>();

        this.VCAS_REF_items_location = new HashSet<VCAS_REF_items_location>();

        this.VCAS_REF_reports_params = new HashSet<VCAS_REF_reports_params>();

        this.VCAS_undepositedFunds = new HashSet<VCAS_undepositedFunds>();

        this.VCAS_capture_payments = new HashSet<VCAS_capture_payments>();

        this.VCAS_forms = new HashSet<VCAS_forms>();

    }


    public int Id { get; set; }

    public string name { get; set; }

    public string location { get; set; }

    public string vendor_Id { get; set; }

    public string app_name { get; set; }

    public string receipt_logo { get; set; }

    public string receipt_footer { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VCAS_debitAccounts> VCAS_debitAccounts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VCAS_district> VCAS_district { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VCAS_issuedChecks> VCAS_issuedChecks { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VCAS_REF_expense_location> VCAS_REF_expense_location { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VCAS_REF_items_location> VCAS_REF_items_location { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VCAS_REF_reports_params> VCAS_REF_reports_params { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VCAS_undepositedFunds> VCAS_undepositedFunds { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VCAS_capture_payments> VCAS_capture_payments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VCAS_forms> VCAS_forms { get; set; }

}

}
