//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCAS_deposit
    {
        public int Id { get; set; }
        public string endind_date { get; set; }
        public string cash_amount { get; set; }
        public string check_amount { get; set; }
        public string visa_debit_amount { get; set; }
        public string visa_credit_amount { get; set; }
        public string bt_amount { get; set; }
        public int FK_councilId { get; set; }
        public Nullable<int> FK_debitAccount { get; set; }
    
        public virtual VCAS_council VCAS_council { get; set; }
    }
}
