
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VCAS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VCAS_reconcile
{

    public int Id { get; set; }

    public int FK_debitAccountsId { get; set; }

    public Nullable<double> bank_ending_amt { get; set; }

    public Nullable<System.DateTime> bank_ending_date { get; set; }

    public Nullable<double> service_charge_amt { get; set; }

    public string service_charge_date { get; set; }

    public Nullable<double> interest_earned_amt { get; set; }

    public string interest_earned_date { get; set; }

    public Nullable<double> difference { get; set; }

    public string reconcile { get; set; }



    public virtual VCAS_debitAccounts VCAS_debitAccounts { get; set; }

}

}
